"""SQLAlchemy declarative base + shared mixins.

A single `Base` is the registry that holds the metadata for every table in the
project. Alembic discovers tables by importing this module (transitively via
`src/db/__init__.py`), so any new model **must** be imported from there or it
will not appear in autogenerated migrations.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func

# Consistent constraint names — required for Alembic to produce reproducible,
# diff-friendly migrations (otherwise Postgres auto-names like `ohlcv_pkey1`
# which become noise in version control).
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """`created_at` / `updated_at` columns maintained by the database itself.

    Using `server_default` and `onupdate` server-side guarantees the timestamps
    are correct even if a row is inserted by a SQL `COPY` (bypassing the ORM).
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
